
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true #开启热部署
  freemarker:
    cache: true
#  data:
#    solr:
#      host: http://localhost:8983/solr/yzx1
swagger:
  production: false #页面不加载缓存，修改即时生效
  basic:
    enable: true
    username: jeecg
    password: jeecg1314
debug: true

log:
  path: c:/emersys/logs/
logging:
  config: classpath:logback-spring.xml

#jeecg专用配置
jeecg :
  path :
    #文件上传根目录 设置
    upload: D://upFiles
    #webapp文件路径
    webapp: D://webapp
    #传真文件共享  服务器ip 文件名
    tiffUrl: \\192.168.100.54\tiffFiles
